"""apply naming conventions

Revision ID: 004c4a238639
Revises: 66f112079451
Create Date: 2026-03-13 22:35:16.879386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004c4a238639'
down_revision: Union[str, Sequence[str], None] = '66f112079451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chemist_prices_chemist_medicine'), table_name='chemist_prices')
    op.drop_constraint(op.f('chemists_license_number_key'), 'chemists', type_='unique')
    op.create_unique_constraint(op.f('uq_chemists_license_number'), 'chemists', ['license_number'])
    op.drop_constraint(op.f('deliveries_order_id_key'), 'deliveries', type_='unique')
    op.create_unique_constraint(op.f('uq_deliveries_order_id'), 'deliveries', ['order_id'])
    op.drop_index(op.f('ix_orders_chemist_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_user_status'), table_name='orders')
    op.drop_index(op.f('ix_prescription_items_prescription'), table_name='prescription_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_prescription_items_prescription'), 'prescription_items', ['prescription_id'], unique=False)
    op.create_index(op.f('ix_orders_user_status'), 'orders', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_chemist_status'), 'orders', ['chemist_id', 'status'], unique=False)
    op.drop_constraint(op.f('uq_deliveries_order_id'), 'deliveries', type_='unique')
    op.create_unique_constraint(op.f('deliveries_order_id_key'), 'deliveries', ['order_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_chemists_license_number'), 'chemists', type_='unique')
    op.create_unique_constraint(op.f('chemists_license_number_key'), 'chemists', ['license_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_chemist_prices_chemist_medicine'), 'chemist_prices', ['chemist_id', 'medicine_id'], unique=False)
    # ### end Alembic commands ###
