"""apply naming conventions

Revision ID: 004c4a238639
Revises: 66f112079451
Create Date: 2026-03-13 22:35:16.879386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004c4a238639'
down_revision: Union[str, Sequence[str], None] = '66f112079451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use IF EXISTS so migrations can be re-run on a clean DB without failing.
    op.execute("DROP INDEX IF EXISTS ix_chemist_prices_chemist_medicine")
    op.execute("ALTER TABLE chemists DROP CONSTRAINT IF EXISTS chemists_license_number_key")
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint c
                JOIN pg_class t ON c.conrelid = t.oid
                WHERE t.relname = 'chemists'
                  AND c.conname = 'uq_chemists_license_number'
            ) THEN
                ALTER TABLE chemists
                ADD CONSTRAINT uq_chemists_license_number UNIQUE (license_number);
            END IF;
        END
        $$;
        """
    )
    op.execute("ALTER TABLE deliveries DROP CONSTRAINT IF EXISTS deliveries_order_id_key")
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint c
                JOIN pg_class t ON c.conrelid = t.oid
                WHERE t.relname = 'deliveries'
                  AND c.conname = 'uq_deliveries_order_id'
            ) THEN
                ALTER TABLE deliveries
                ADD CONSTRAINT uq_deliveries_order_id UNIQUE (order_id);
            END IF;
        END
        $$;
        """
    )
    op.execute("DROP INDEX IF EXISTS ix_orders_chemist_status")
    op.execute("DROP INDEX IF EXISTS ix_orders_user_status")
    op.execute("DROP INDEX IF EXISTS ix_prescription_items_prescription")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE INDEX IF NOT EXISTS ix_prescription_items_prescription ON prescription_items (prescription_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_orders_user_status ON orders (user_id, status)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_orders_chemist_status ON orders (chemist_id, status)")
    op.execute("ALTER TABLE deliveries DROP CONSTRAINT IF EXISTS uq_deliveries_order_id")
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint c
                JOIN pg_class t ON c.conrelid = t.oid
                WHERE t.relname = 'deliveries'
                  AND c.conname = 'deliveries_order_id_key'
            ) THEN
                ALTER TABLE deliveries
                ADD CONSTRAINT deliveries_order_id_key UNIQUE (order_id);
            END IF;
        END
        $$;
        """
    )
    op.execute("ALTER TABLE chemists DROP CONSTRAINT IF EXISTS uq_chemists_license_number")
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint c
                JOIN pg_class t ON c.conrelid = t.oid
                WHERE t.relname = 'chemists'
                  AND c.conname = 'chemists_license_number_key'
            ) THEN
                ALTER TABLE chemists
                ADD CONSTRAINT chemists_license_number_key UNIQUE (license_number);
            END IF;
        END
        $$;
        """
    )
    op.execute("CREATE INDEX IF NOT EXISTS ix_chemist_prices_chemist_medicine ON chemist_prices (chemist_id, medicine_id)")
    # ### end Alembic commands ###
